services:
  mongodb:
    image: mongo:latest
    container_name: mutiny-cart-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: mutiny-cart-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_SITE_COOKIESECRET=secret
      - ME_CONFIG_SITE_SESSIONSECRET=secret
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data:
    name: mutiny-cart-mongodb-data 